[package]
name = "rs_print_pixels_term"
version = "0.1.0"
authors = ["ooboh3eesheicie7"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
crossterm = "0.17"
ctrlc = "3.1.4"